export interface Livery {
  id: string
  name: string
  tagline: string
  logoText: string
  fontFamily: string
  colors: Record<string, string>
}

export const LIVERIES: Record<string, Livery> = {
  nostradata: {
    id: 'nostradata',
    name: 'NostraData',
    tagline: 'Shopper Intelligence',
    logoText: 'Shopper360',
    fontFamily: '"Inter", ui-sans-serif, system-ui, sans-serif',
    colors: {
      'theme-primary': '#0A8BA8',
      'theme-primary-light': '#0FB5D4',
      'theme-primary-foreground': '#FFFFFF',
      'theme-accent': '#10B39B',
      'theme-accent-foreground': '#FFFFFF',
      'theme-ring': '#0A8BA8',
      'theme-sidebar-from': '#0F172A',
      'theme-sidebar-to': '#1E293B',
      'theme-hero-from': '#0F172A',
      'theme-hero-mid': '#0A8BA8',
      'theme-hero-to': '#10B39B',
      'theme-chart-1': '#0A8BA8',
      'theme-chart-2': '#10B39B',
      'theme-chart-3': '#F59E0B',
      'theme-chart-4': '#EF4444',
      'theme-chart-5': '#8B5CF6',
      'theme-seg-power': '#10B981',
      'theme-seg-regular': '#3B82F6',
      'theme-seg-occasional': '#F59E0B',
      'theme-seg-new': '#8B5CF6',
      'theme-seg-atrisk': '#EF4444',
    },
  },
  priceline: {
    id: 'priceline',
    name: 'Priceline Pharmacy',
    tagline: 'Shopper Insights',
    logoText: 'Shopper360',
    fontFamily: '"Helvetica Neue", Helvetica, Arial, sans-serif',
    colors: {
      'theme-primary': '#E31C79',
      'theme-primary-light': '#F04E98',
      'theme-primary-foreground': '#FFFFFF',
      'theme-accent': '#00A3E0',
      'theme-accent-foreground': '#FFFFFF',
      'theme-ring': '#E31C79',
      'theme-sidebar-from': '#1A0A12',
      'theme-sidebar-to': '#2D1220',
      'theme-hero-from': '#1A0A12',
      'theme-hero-mid': '#E31C79',
      'theme-hero-to': '#00A3E0',
      'theme-chart-1': '#E31C79',
      'theme-chart-2': '#00A3E0',
      'theme-chart-3': '#F59E0B',
      'theme-chart-4': '#EF4444',
      'theme-chart-5': '#8B5CF6',
      'theme-seg-power': '#10B981',
      'theme-seg-regular': '#00A3E0',
      'theme-seg-occasional': '#F59E0B',
      'theme-seg-new': '#8B5CF6',
      'theme-seg-atrisk': '#EF4444',
    },
  },
  amcal: {
    id: 'amcal',
    name: 'Amcal',
    tagline: 'Customer Intelligence',
    logoText: 'Shopper360',
    fontFamily: '"Avenir", "Inter", ui-sans-serif, system-ui, sans-serif',
    colors: {
      'theme-primary': '#00A8E5',
      'theme-primary-light': '#33BFEF',
      'theme-primary-foreground': '#FFFFFF',
      'theme-accent': '#6DC24B',
      'theme-accent-foreground': '#FFFFFF',
      'theme-ring': '#00A8E5',
      'theme-sidebar-from': '#001F33',
      'theme-sidebar-to': '#003652',
      'theme-hero-from': '#001F33',
      'theme-hero-mid': '#00A8E5',
      'theme-hero-to': '#6DC24B',
      'theme-chart-1': '#00A8E5',
      'theme-chart-2': '#6DC24B',
      'theme-chart-3': '#F59E0B',
      'theme-chart-4': '#EF4444',
      'theme-chart-5': '#8B5CF6',
      'theme-seg-power': '#6DC24B',
      'theme-seg-regular': '#00A8E5',
      'theme-seg-occasional': '#F59E0B',
      'theme-seg-new': '#8B5CF6',
      'theme-seg-atrisk': '#EF4444',
    },
  },
}
