export interface Livery {
  id: string
  name: string
  tagline: string
  logoText: string
  logoShort: string
  logoWhite: string
  logoColor: string
  fontFamily: string
  colors: Record<string, string>
}

export const LIVERIES: Record<string, Livery> = {
  nostradata: {
    id: 'nostradata',
    name: 'NostraData',
    tagline: 'Shopper Intelligence',
    logoText: 'Shopper360',
    logoShort: 'S3',
    logoWhite: '/logos/nostradata-white.svg',
    logoColor: '/logos/nostradata-color.svg',
    fontFamily: '"Inter", ui-sans-serif, system-ui, sans-serif',
    colors: {
      'theme-primary': '#0A8BA8',
      'theme-primary-light': '#0FB5D4',
      'theme-primary-foreground': '#FFFFFF',
      'theme-accent': '#10B39B',
      'theme-accent-foreground': '#FFFFFF',
      'theme-ring': '#0A8BA8',
      'theme-sidebar-from': '#0F172A',
      'theme-sidebar-to': '#1E293B',
      'theme-hero-from': '#0F172A',
      'theme-hero-mid': '#0A8BA8',
      'theme-hero-to': '#10B39B',
      'theme-chart-1': '#0A8BA8',
      'theme-chart-2': '#10B39B',
      'theme-chart-3': '#F59E0B',
      'theme-chart-4': '#EF4444',
      'theme-chart-5': '#8B5CF6',
      'theme-seg-power': '#10B981',
      'theme-seg-regular': '#3B82F6',
      'theme-seg-occasional': '#F59E0B',
      'theme-seg-new': '#8B5CF6',
      'theme-seg-atrisk': '#EF4444',
    },
  },
  iqvia: {
    id: 'iqvia',
    name: 'IQVIA Consumer Health',
    tagline: 'Consumer Health Intelligence',
    logoText: 'Shopper360',
    logoShort: 'IQ',
    logoWhite: '/logos/iqvia-white.svg',
    logoColor: '/logos/iqvia-color.svg',
    fontFamily: '"Arial", "Helvetica Neue", Helvetica, sans-serif',
    colors: {
      'theme-primary': '#00A3E0',
      'theme-primary-light': '#33B8E8',
      'theme-primary-foreground': '#FFFFFF',
      'theme-accent': '#00D4AA',
      'theme-accent-foreground': '#FFFFFF',
      'theme-ring': '#00A3E0',
      'theme-sidebar-from': '#0C2340',
      'theme-sidebar-to': '#1A365D',
      'theme-hero-from': '#0C2340',
      'theme-hero-mid': '#00A3E0',
      'theme-hero-to': '#00D4AA',
      'theme-chart-1': '#00A3E0',
      'theme-chart-2': '#00D4AA',
      'theme-chart-3': '#F59E0B',
      'theme-chart-4': '#EF4444',
      'theme-chart-5': '#8B5CF6',
      'theme-seg-power': '#00D4AA',
      'theme-seg-regular': '#00A3E0',
      'theme-seg-occasional': '#F59E0B',
      'theme-seg-new': '#8B5CF6',
      'theme-seg-atrisk': '#EF4444',
    },
  },
  chemistwarehouse: {
    id: 'chemistwarehouse',
    name: 'Chemist Warehouse',
    tagline: 'Shopper Intelligence',
    logoText: 'Shopper360',
    logoShort: 'CW',
    logoWhite: '/logos/cw-white.svg',
    logoColor: '/logos/cw-color.svg',
    fontFamily: '"Arial", "Helvetica Neue", Helvetica, sans-serif',
    colors: {
      'theme-primary': '#E30019',
      'theme-primary-light': '#FF1A33',
      'theme-primary-foreground': '#FFFFFF',
      'theme-accent': '#FFCC00',
      'theme-accent-foreground': '#1A1A1A',
      'theme-ring': '#E30019',
      'theme-sidebar-from': '#1A1A1A',
      'theme-sidebar-to': '#2D2D2D',
      'theme-hero-from': '#1A1A1A',
      'theme-hero-mid': '#E30019',
      'theme-hero-to': '#8B0010',
      'theme-chart-1': '#E30019',
      'theme-chart-2': '#FFCC00',
      'theme-chart-3': '#3B82F6',
      'theme-chart-4': '#10B981',
      'theme-chart-5': '#8B5CF6',
      'theme-seg-power': '#10B981',
      'theme-seg-regular': '#3B82F6',
      'theme-seg-occasional': '#FFCC00',
      'theme-seg-new': '#8B5CF6',
      'theme-seg-atrisk': '#E30019',
    },
  },
}
